name:                hlog
version:             0.1.0.0
github:              "g3rrit/hlog"
license:             BSD3
author:              "Gerrit Proessl"
maintainer:          "gerrit.proessl@gmail.com"
copyright:           "2022 Gerrit Proessl"

description:         Please see the README on GitHub at <https://github.com/g3rrit/hlog#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  hlog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
